import { readFile, rm, stat, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { body, section } from "../output.js";

type CleanOptions = {
  /** Consumer project root (default: cwd). */
  dir?: string;
  /** Apply the changes; without it, dry-run (print only). */
  force?: boolean;
};

// The five SVGs create-next-app drops into public/. Filenames are specific
// enough to be safe, and the dry-run + --force gate is the real guard.
const DEFAULT_SVGS = [
  "next.svg",
  "vercel.svg",
  "file.svg",
  "globe.svg",
  "window.svg",
];

const MINIMAL_PAGE = `export default function Home() {
  return (
    <main>
      <h1>New app</h1>
    </main>
  );
}
`;

async function pathExists(p: string): Promise<boolean> {
  try {
    await stat(p);
    return true;
  } catch {
    return false;
  }
}

async function readIf(p: string): Promise<string | null> {
  try {
    return await readFile(p, "utf8");
  } catch {
    return null;
  }
}

type Action = {
  verb: "remove" | "reset";
  path: string;
  why: string;
  run: () => Promise<void>;
};

/**
 * Strips create-next-app boilerplate so a fresh project starts clean before you
 * dress it in a design system. Content-matched: files you've edited are left
 * untouched. Dry-run by default - re-run with --force to apply. (Dogfood #2b.)
 */
export async function clean(opts: CleanOptions): Promise<void> {
  const root = opts.dir ?? process.cwd();
  const appDir = (await pathExists(join(root, "src", "app")))
    ? join(root, "src", "app")
    : join(root, "app");
  const rel = (p: string) => relative(root, p).replace(/\\/g, "/");

  const actions: Action[] = [];

  // 1. Default public SVGs.
  for (const svg of DEFAULT_SVGS) {
    const p = join(root, "public", svg);
    if (await pathExists(p)) {
      actions.push({
        verb: "remove",
        path: `public/${svg}`,
        why: "create-next-app default asset",
        run: () => rm(p),
      });
    }
  }

  // 2. Default landing page → minimal placeholder (only if unedited).
  const pagePath = join(appDir, "page.tsx");
  const pageSrc = await readIf(pagePath);
  if (pageSrc && /Get started by editing|Deploy now|Read our docs/.test(pageSrc)) {
    actions.push({
      verb: "reset",
      path: rel(pagePath),
      why: "default landing → minimal placeholder",
      run: () => writeFile(pagePath, MINIMAL_PAGE, "utf8"),
    });
  }

  // 3. Layout metadata still says "Create Next App".
  const layoutPath = join(appDir, "layout.tsx");
  const layoutSrc = await readIf(layoutPath);
  if (
    layoutSrc &&
    /"Create Next App"|"Generated by create next app"/.test(layoutSrc)
  ) {
    actions.push({
      verb: "reset",
      path: rel(layoutPath),
      why: 'metadata "Create Next App" → neutral',
      run: () =>
        writeFile(
          layoutPath,
          layoutSrc
            .replace(/"Create Next App"/g, '"App"')
            .replace(/"Generated by create next app"/g, '""'),
          "utf8",
        ),
    });
  }

  // 4. Default README.
  const readmePath = join(root, "README.md");
  const readmeSrc = await readIf(readmePath);
  if (readmeSrc && /create-next-app/.test(readmeSrc) && /Getting Started/.test(readmeSrc)) {
    actions.push({
      verb: "remove",
      path: "README.md",
      why: "create-next-app default README",
      run: () => rm(readmePath),
    });
  }

  if (actions.length === 0) {
    console.log(section("Clean up scaffold"));
    console.log(body("Nothing to clean - this project is already tidy."));
    console.log("");
    return;
  }

  console.log(
    section(opts.force ? "Cleaned up scaffold" : "Clean up scaffold (dry run)"),
  );
  const pad = Math.max(...actions.map((a) => a.path.length));
  for (const a of actions) {
    const mark = opts.force ? "✓" : "•";
    console.log(
      body(`${mark} ${a.verb.padEnd(6)} ${a.path.padEnd(pad)}   ${a.why}`),
    );
    if (opts.force) await a.run();
  }
  console.log("");
  console.log(
    body(
      opts.force
        ? `Done - ${actions.length} item(s) tidied.`
        : "Dry run - nothing changed. Re-run with `synthesisui clean --force` to apply.",
    ),
  );
  console.log("");
}
