import type { RegistryPayload } from "./types.js";

const kebab = (v: string) =>
  v.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

const list = (items: string[]) =>
  items.length ? items.map((i) => `\`${i}\``).join(", ") : "_(none)_";

/**
 * Builds GUIDE.md — instructions *for the agent* on how to build components
 * that follow the design system. This is the piece that makes "I create the
 * components with claude-code" work: the tokens alone are not enough, the agent
 * needs the rules and the real vocabulary (semantic token names and recipes).
 */
export function buildGuide(payload: RegistryPayload): string {
  const { document: doc, slug, name, version } = payload;
  const { meta, foundations, motion, components } = doc;

  const semanticRoles = Object.keys(foundations.color.semantic);
  const hasAlt =
    foundations.color.semanticAlt &&
    Object.keys(foundations.color.semanticAlt).length > 0;
  const altScheme = meta.scheme === "light" ? "dark" : "light";
  const hasTailwind = "theme.css" in payload.artifacts;

  const componentLines = Object.entries(components).map(([cname, recipe]) => {
    const cls = `.ds-${kebab(cname)}`;
    const axes = Object.entries(recipe.variants).map(([axis, opts]) => {
      const options = Object.keys(opts);
      return `\`data-${kebab(axis)}="${options.join("|")}"\``;
    });
    const variantsText = axes.length ? ` — variants: ${axes.join(", ")}` : "";
    return `- **${cname}** (\`${cls}\`)${variantsText}\n  ${recipe.description}`;
  });

  const artifactList = Object.keys(payload.artifacts)
    .map((f) => `\`${f}\``)
    .join(", ");

  return `# Design System: ${name}

> Generated by \`synthesisui add ${slug}\` (v${version}). **Do not edit by hand** —
> run \`synthesisui add ${slug}\` again to update.

${meta.tagline}

**Mood:** ${meta.mood.join(" · ")}
**Default scheme:** ${meta.scheme}${hasAlt ? ` (supports a toggle to ${altScheme})` : ""}
${meta.sourceUrl ? `**Reinterpretation of:** ${meta.sourceUrl}` : "**Original system.**"}

${meta.narrative}

---

## How to apply

1. Import the tokens once in your project's global CSS:
   \`\`\`css
   @import "./_synthesisui/ds/${slug}/tokens.css";
   \`\`\`
   (adjust the relative path to where your CSS lives.)

2. Wrap the tree that should use the system with the scope attribute:
   \`\`\`html
   <div data-ds="${slug}">…your UI here…</div>
   \`\`\`
   All \`--ds-*\` custom properties and \`.ds-*\` classes only apply inside that scope.
${
  hasAlt
    ? `
3. Light/dark: an ancestor with \`data-scheme="${altScheme}"\` switches the neutral roles to the opposite mode.
   \`\`\`html
   <div data-scheme="${altScheme}"><div data-ds="${slug}">…</div></div>
   \`\`\`
`
    : ""
}${
    hasTailwind
      ? `
## Using it with Tailwind v4 (optional)

If the project uses Tailwind v4, import \`theme.css\` after \`tailwindcss\` and \`tokens.css\`:
\`\`\`css
@import "tailwindcss";
@import "./_synthesisui/ds/${slug}/tokens.css";
@import "./_synthesisui/ds/${slug}/theme.css";
\`\`\`
This maps the DS tokens onto Tailwind's theme, so inside \`[data-ds="${slug}"]\` you can use
utilities such as \`bg-primary\`, \`text-foreground\`, \`p-md\`, \`rounded-lg\`, \`shadow-*\`,
\`font-*\` and \`ease-*\` — all backed by the design system. Prefer these utilities (or the
\`.ds-*\` recipes) over raw values.

---
`
      : ""
}
This is **v${version}**. The stable entrypoints at \`_synthesisui/ds/${slug}/\` (the
\`tokens.css\`/\`theme.css\` re-exports, plus \`.lock\`) always point at the active version — import
those, not the versioned ones. The pinned files for this version — ${artifactList},
\`design-system.json\` (canonical source of truth), \`GUIDE.md\` (this file) — live in
\`_synthesisui/ds/${slug}/v${version}/\`.

---

## Rules (follow them when creating components)

- **Always use semantic tokens**, never raw values nor primitives directly.
  Color: \`var(--ds-color-semantic-<role>)\`. The roles are: ${list(semanticRoles)}.
- Primitives (\`--ds-color-<palette>-<step>\`) exist but should **not** be referenced directly —
  they feed the semantic roles.
- Spacing → \`var(--ds-spacing-<key>)\`: ${list(Object.keys(foundations.spacing))}.
- Radius → \`var(--ds-radius-<key>)\`: ${list(Object.keys(foundations.radius))}.
- Shadow → \`var(--ds-shadow-<key>)\`: ${list(Object.keys(foundations.shadow))}.
- Typography: families \`--ds-typography-families-{display,body,mono}\` (${foundations.typography.families.display}, ${foundations.typography.families.body}, ${foundations.typography.families.mono});
  scale \`--ds-typography-scale-<key>-font-size\` etc.: ${list(Object.keys(foundations.typography.scale))}.
- Motion: durations \`--ds-motion-durations-<key>\` (${list(Object.keys(motion.durations))}) and
  easings \`--ds-motion-easings-<key>\` (${list(Object.keys(motion.easings))}).
- When **creating a new component** the DS does not cover yet: compose it from these semantic
  tokens to inherit the system's identity; do not invent colors/measures outside the scale.

---

## Where to preview

**Preview in isolation, never on a real page.** When creating or demoing a component, generate a
dedicated sample page — \`app/synthesisui-samples/<component>/\` in the Next.js App Router (or the
equivalent samples route/folder in the project's stack). **Do not** apply the component to real
production pages (home, layout, existing routes) unless explicitly asked. Samples let you review the
component in the context of the design system without touching the app.

---

## Ready-made components

Each recipe becomes a \`.ds-<name>\` class (inside the \`[data-ds="${slug}"]\` scope).
Variants are \`data-<axis>="<option>"\` attributes; states (hover/focus/active/disabled) ship in the CSS.

${componentLines.join("\n\n")}

---

_Full canonical source of truth (including values and keyframes) in \`design-system.json\`._
`;
}
